### ISSUE TITLE
Place doen't render propperly

### ISSUE THREAD

**Issue by OhaDerErste** [cerus/minecraft-place#1]
![image](https://user-images.githubusercontent.com/77100649/161419890-8df123a7-a080-4ecc-ab94-7a7384947df7.png)

**Comment by OhaDerErste** [comment]
Looks normal when I start the server and it gets worse over time
![image](https://user-images.githubusercontent.com/77100649/161420013-4196b934-3cd3-4a07-b383-6b22407c7ebe.png)

**Comment by cerus** [comment]
Hey, thanks for bringing this issue to my attention. Did I understand correctly that everything looks normal on startup and gets worse and worse the longer it is running?

**Comment by cerus** [comment]
I think I see what the problem is. In the meantime while I'm working on a fix you can try it on 1.16.5, it works on that version.

**Comment by cerus** [comment]
Update: This issue has been fixed with the latest `maps` release! Please [download it here](https://github.com/cerus/maps/releases/download/2.0.0-SNAPSHOT-pre3/maps-plugin.jar) and let me know if this resolves your issue.

**Comment by OhaDerErste** [comment]
works now, thanks!
